// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package diagnostic

import (
  "encoding/xml"
)

type Diagnostic struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/diagnostic diagnostic"`
  DiagnosticComplexType
}

type DiagnosticComplexType struct {
  Uri string `xml:"uri"`
  Details string `xml:"details,omitempty"`
  Message string `xml:"message,omitempty"`
}

type Details struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/diagnostic details"`
  Text string `xml:",chardata"`
}

type Message struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/diagnostic message"`
  Text string `xml:",chardata"`
}

type Uri struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/diagnostic uri"`
  Text string `xml:",chardata"`
}

