// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package diagnostic

import (
  "encoding/xml"
)

type Diagnostic struct {
  XMLName xml.Name `xml:"diagnostic" json:"-"`
  DiagnosticComplexType
}

type DiagnosticComplexType struct {
  Uri string `xml:"uri" json:"uri"`
  Details string `xml:"details,omitempty" json:"details,omitempty"`
  Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type Details struct {
  XMLName xml.Name `xml:"details" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Message struct {
  XMLName xml.Name `xml:"message" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Uri struct {
  XMLName xml.Name `xml:"uri" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

