// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package facetedResults

import (
  "encoding/xml"
)

type FacetedResults struct {
  XMLName xml.Name `xml:"facetedResults" json:"-"`
  FacetedResultsDefinition
}

type FacetedResultsDefinition struct {
  Datasource []DatasourceDefinition `xml:"datasource,omitempty" json:"datasource,omitempty"`
  Facet []FacetDefinition `xml:"facet,omitempty" json:"facet,omitempty"`
}

type DatasourceDefinition struct {
  DatasourceDisplayLabel string `xml:"datasourceDisplayLabel,omitempty" json:"datasourceDisplayLabel,omitempty"`
  DatasourceDescription string `xml:"datasourceDescription,omitempty" json:"datasourceDescription,omitempty"`
  BaseURL string `xml:"baseURL,omitempty" json:"baseURL,omitempty"`
  Facets FacetsDefinition `xml:"facets" json:"facets"`
}

type FacetsDefinition struct {
  Facet []FacetDefinition `xml:"facet,omitempty" json:"facet,omitempty"`
}

type FacetDefinition struct {
  FacetDisplayLabel string `xml:"facetDisplayLabel,omitempty" json:"facetDisplayLabel,omitempty"`
  FacetDescription string `xml:"facetDescription,omitempty" json:"facetDescription,omitempty"`
  Index string `xml:"index,omitempty" json:"index,omitempty"`
  Relation string `xml:"relation,omitempty" json:"relation,omitempty"`
  Terms TermsDefinition `xml:"terms" json:"terms"`
}

type TermsDefinition struct {
  Term []TermDefinition `xml:"term,omitempty" json:"term,omitempty"`
}

type TermDefinition struct {
  ActualTerm string `xml:"actualTerm" json:"actualTerm"`
  Query string `xml:"query,omitempty" json:"query,omitempty"`
  RequestUrl string `xml:"requestUrl,omitempty" json:"requestUrl,omitempty"`
  Count int64 `xml:"count" json:"count"`
}

type ActualTerm struct {
  XMLName xml.Name `xml:"actualTerm" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type BaseURL struct {
  XMLName xml.Name `xml:"baseURL" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Count struct {
  XMLName xml.Name `xml:"count" json:"-"`
  Text int64 `xml:",chardata" json:"#text,omitempty"`
}

type Datasource struct {
  XMLName xml.Name `xml:"datasource" json:"-"`
  DatasourceDefinition
}

type DatasourceDescription struct {
  XMLName xml.Name `xml:"datasourceDescription" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type DatasourceDisplayLabel struct {
  XMLName xml.Name `xml:"datasourceDisplayLabel" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Facet struct {
  XMLName xml.Name `xml:"facet" json:"-"`
  FacetDefinition
}

type FacetBaseURL struct {
  XMLName xml.Name `xml:"facetBaseURL" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type FacetDisplayLabel struct {
  XMLName xml.Name `xml:"facetDisplayLabel" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type FacetDescription struct {
  XMLName xml.Name `xml:"facetDescription" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Facets struct {
  XMLName xml.Name `xml:"facets" json:"-"`
  FacetsDefinition
}

type Index struct {
  XMLName xml.Name `xml:"index" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Term struct {
  XMLName xml.Name `xml:"term" json:"-"`
  TermDefinition
}

type Terms struct {
  XMLName xml.Name `xml:"terms" json:"-"`
  TermsDefinition
}

type Query struct {
  XMLName xml.Name `xml:"query" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Relation struct {
  XMLName xml.Name `xml:"relation" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type RequestUrl struct {
  XMLName xml.Name `xml:"requestUrl" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

