// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package facetedResults

import (
  "encoding/xml"
)

type FacetedResults struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults facetedResults"`
  FacetedResultsDefinition
}

type FacetedResultsDefinition struct {
  Datasource []DatasourceDefinition `xml:"datasource,omitempty"`
  Facet []FacetDefinition `xml:"facet,omitempty"`
}

type DatasourceDefinition struct {
  DatasourceDisplayLabel string `xml:"datasourceDisplayLabel,omitempty"`
  DatasourceDescription string `xml:"datasourceDescription,omitempty"`
  BaseURL string `xml:"baseURL,omitempty"`
  Facets FacetsDefinition `xml:"facets"`
}

type FacetsDefinition struct {
  Facet []FacetDefinition `xml:"facet,omitempty"`
}

type FacetDefinition struct {
  FacetDisplayLabel string `xml:"facetDisplayLabel,omitempty"`
  FacetDescription string `xml:"facetDescription,omitempty"`
  Index string `xml:"index,omitempty"`
  Relation string `xml:"relation,omitempty"`
  Terms TermsDefinition `xml:"terms"`
}

type TermsDefinition struct {
  Term []TermDefinition `xml:"term,omitempty"`
}

type TermDefinition struct {
  ActualTerm string `xml:"actualTerm"`
  Query string `xml:"query,omitempty"`
  RequestUrl string `xml:"requestUrl,omitempty"`
  Count int64 `xml:"count"`
}

type ActualTerm struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults actualTerm"`
  Text string `xml:",chardata"`
}

type BaseURL struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults baseURL"`
  Text string `xml:",chardata"`
}

type Count struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults count"`
  Text int64 `xml:",chardata"`
}

type Datasource struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults datasource"`
  DatasourceDefinition
}

type DatasourceDescription struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults datasourceDescription"`
  Text string `xml:",chardata"`
}

type DatasourceDisplayLabel struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults datasourceDisplayLabel"`
  Text string `xml:",chardata"`
}

type Facet struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults facet"`
  FacetDefinition
}

type FacetBaseURL struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults facetBaseURL"`
  Text string `xml:",chardata"`
}

type FacetDisplayLabel struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults facetDisplayLabel"`
  Text string `xml:",chardata"`
}

type FacetDescription struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults facetDescription"`
  Text string `xml:",chardata"`
}

type Facets struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults facets"`
  FacetsDefinition
}

type Index struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults index"`
  Text string `xml:",chardata"`
}

type Term struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults term"`
  TermDefinition
}

type Terms struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults terms"`
  TermsDefinition
}

type Query struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults query"`
  Text string `xml:",chardata"`
}

type Relation struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults relation"`
  Text string `xml:",chardata"`
}

type RequestUrl struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/facetedResults requestUrl"`
  Text string `xml:",chardata"`
}

