// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//  Written by: Ed Davidson (OCLC), Schema validated using XMLPad v3.0.2.1 (Build 07/05/2008) 
//  Updated by: Abhijeet Roy (OCLC), Version 2021-2 June 2022, Schema validated using Eclipse IDE Version: 2021-09 (4.21.0) 
//  ...................................... 
//  ISO 18626 "Inter Library Loan Protocol 
//  ...................................... 
// 	Purpose: XML schema for ILL protocol ISO 18626
// 	Dependencies: None
// 	Change History:
// 	    Version 2021-2 June 2022
// 	        Corrections to errors in 2021-1 XSD for the 2021 revision of standard.
// 	        Request
// 	            Updated requestHeader to header of type type_requestHeader
// 	            Changed serviceInfo/serviceType to type to type_serviceType
// 	        SupplyingAgencyMessage
// 	            Updated requestHeader to header of type type_supplyingAgencyMessageHeader
// 	            Added name attribute to retryInfo/serviceType and changed the type to type_serviceType
// 	            Added name attribute to deliveryInfo/serviceType and changed the type to type_serviceType
// 	        RequestingAgencyMessage
// 	            Updated requestHeader to header of type type_requestingAgencyMessageHeader
// 		Version 2021-1 January 2021 (aka version 1.3)
// 			Changes for the 2021 Revision of the standard
// 			NOTE: We now name XSDs after the publication year of the Revision of the standard plus a version number for minor revision of the schema for that version of the standard
// 			thus what would have been XSD Version "1_3_2021" is now named "2021-1"
// 			Request
// 				DIS: Updated Header
// 					Added ConsortialId
// 					Made SupplyingAgencyId optional (for transfer requests that don't require a supplier)
// 					Made MultipleItemRequestId optional (erroneously mandatory in previous XSD)
// 				FINAL: Replaced generic message Header structure with message specific headers as the headers have diverged since initial version of protocol
// 					requestHeader
// 					supplyingAgencyMessageHeader
// 					requestingAgencyMessageHeader
// 				BibliographicInfo
// 					Changed field sequence of BibliographicItemId to match the order of elements in the document
// 					Added AuthorId (to hold an ISNI (ISO-27729))
// 					Made Volume repeatable
// 				Updated SupplierInfo
// 					Restricted sortOrder to a non-negative value (0 ->)
// 				Updated RequestedDeliveryInfo
// 					Restricted sortOrder to a non-negative value (0 ->)
// 					Added deliveryMethod
// 					Added courierName
// 				Added Action=HoldReturn
// 			SupplyingAgencyMessage
// 				Added RetryInfo structure
// 				Moved OfferedCosts, RetryBefore, RetryAfter from MessageInfo to RetryInfo
// 				Updated  DeliveryInfo
// 					Renamed sentVia to deliveryMethod
// 					Renamed deliveredFormat to itemFormat
// 					Added URL
// 					Added address
// 					Added serviceType
// 					Added paymentMethod
// 				Added ShippingInfo structure
// 				Added Status=HoldReturn
// 				Added Status=ReleaseHoldReturn
// 			RequestingAgencyMessage
// 				Added Action = HoldReturn
// 				PhysicalAddress/Region changed from scheme/value pair to plain string
// 		Version 1.2 November 2017
// 			Changed in order to describe the 2017 Minor revision of the standard
// 			Added the following four new data elements
// 				header
// 					multipleItemRequestId
// 				serviceType
// 					requestSubType
// 					startDate
// 					endDate							
// 		Version 1.1 March 2014
// 			Changed the way enumerations were defined so that they would build correctly when using JAXB
// 			This file describes 2014 version of the standard
// 		Version 1.0 2014
// 			First Cut 
//  
package iso18626

import (
  "encoding/xml"
  utils "github.com/indexdata/go-utils/utils"
)


type ISO18626Message struct {
  XMLName xml.Name `xml:"ISO18626Message" json:"-"`
  Request *Request `xml:"request,omitempty" json:"request,omitempty"`
  RequestConfirmation *RequestConfirmation `xml:"requestConfirmation,omitempty" json:"requestConfirmation,omitempty"`
  SupplyingAgencyMessage *SupplyingAgencyMessage `xml:"supplyingAgencyMessage,omitempty" json:"supplyingAgencyMessage,omitempty"`
  SupplyingAgencyMessageConfirmation *SupplyingAgencyMessageConfirmation `xml:"supplyingAgencyMessageConfirmation,omitempty" json:"supplyingAgencyMessageConfirmation,omitempty"`
  RequestingAgencyMessage *RequestingAgencyMessage `xml:"requestingAgencyMessage,omitempty" json:"requestingAgencyMessage,omitempty"`
  RequestingAgencyMessageConfirmation *RequestingAgencyMessageConfirmation `xml:"requestingAgencyMessageConfirmation,omitempty" json:"requestingAgencyMessageConfirmation,omitempty"`
  Version utils.PrefixAttr `xml:"version,attr" json:"@version"`
}


type Request struct {
  XMLName xml.Name `xml:"request" json:"-"`
  Header TypeRequestHeader `xml:"header" json:"header"`
  BibliographicInfo BibliographicInfo `xml:"bibliographicInfo" json:"bibliographicInfo"`
  PublicationInfo *PublicationInfo `xml:"publicationInfo,omitempty" json:"publicationInfo,omitempty"`
  ServiceInfo ServiceInfo `xml:"serviceInfo" json:"serviceInfo"`
  SupplierInfo []SupplierInfo `xml:"supplierInfo,omitempty" json:"supplierInfo,omitempty"`
  RequestedDeliveryInfo []RequestedDeliveryInfo `xml:"requestedDeliveryInfo,omitempty" json:"requestedDeliveryInfo,omitempty"`
  RequestingAgencyInfo *RequestingAgencyInfo `xml:"requestingAgencyInfo,omitempty" json:"requestingAgencyInfo,omitempty"`
  PatronInfo *PatronInfo `xml:"patronInfo,omitempty" json:"patronInfo,omitempty"`
  BillingInfo *BillingInfo `xml:"billingInfo,omitempty" json:"billingInfo,omitempty"`
}


type RequestConfirmation struct {
  XMLName xml.Name `xml:"requestConfirmation" json:"-"`
  ConfirmationHeader ConfirmationHeader `xml:"confirmationHeader" json:"confirmationHeader"`
  ErrorData []ErrorData `xml:"errorData,omitempty" json:"errorData,omitempty"`
}


type SupplyingAgencyMessage struct {
  XMLName xml.Name `xml:"supplyingAgencyMessage" json:"-"`
  Header TypeSupplyingAgencyMessageHeader `xml:"header" json:"header"`
  MessageInfo MessageInfo `xml:"messageInfo" json:"messageInfo"`
  StatusInfo StatusInfo `xml:"statusInfo" json:"statusInfo"`
  RetryInfo *RetryInfo `xml:"retryInfo,omitempty" json:"retryInfo,omitempty"`
  DeliveryInfo *DeliveryInfo `xml:"deliveryInfo,omitempty" json:"deliveryInfo,omitempty"`
  ShippingInfo *ShippingInfo `xml:"shippingInfo,omitempty" json:"shippingInfo,omitempty"`
  ReturnInfo *ReturnInfo `xml:"returnInfo,omitempty" json:"returnInfo,omitempty"`
}


type SupplyingAgencyMessageConfirmation struct {
  XMLName xml.Name `xml:"supplyingAgencyMessageConfirmation" json:"-"`
  ConfirmationHeader ConfirmationHeader `xml:"confirmationHeader" json:"confirmationHeader"`
  ReasonForMessage *TypeReasonForMessage `xml:"reasonForMessage,omitempty" json:"reasonForMessage,omitempty"`
  ErrorData []ErrorData `xml:"errorData,omitempty" json:"errorData,omitempty"`
}


type RequestingAgencyMessage struct {
  XMLName xml.Name `xml:"requestingAgencyMessage" json:"-"`
  Header TypeRequestingAgencyMessageHeader `xml:"header" json:"header"`
  Action TypeAction `xml:"action" json:"action"`
  Note string `xml:"note,omitempty" json:"note,omitempty"`
}


type RequestingAgencyMessageConfirmation struct {
  XMLName xml.Name `xml:"requestingAgencyMessageConfirmation" json:"-"`
  ConfirmationHeader ConfirmationHeader `xml:"confirmationHeader" json:"confirmationHeader"`
  Action *TypeAction `xml:"action,omitempty" json:"action,omitempty"`
  ErrorData []ErrorData `xml:"errorData,omitempty" json:"errorData,omitempty"`
}

type Action struct {
  XMLName xml.Name `xml:"action" json:"-"`
  TypeAction
}


type Address struct {
  XMLName xml.Name `xml:"address" json:"-"`
  ElectronicAddress *ElectronicAddress `xml:"electronicAddress,omitempty" json:"electronicAddress,omitempty"`
  PhysicalAddress *PhysicalAddress `xml:"physicalAddress,omitempty" json:"physicalAddress,omitempty"`
}


type BibliographicItemId struct {
  XMLName xml.Name `xml:"bibliographicItemId" json:"-"`
  BibliographicItemIdentifierCode TypeSchemeValuePair `xml:"bibliographicItemIdentifierCode" json:"bibliographicItemIdentifierCode"`
  BibliographicItemIdentifier string `xml:"bibliographicItemIdentifier" json:"bibliographicItemIdentifier"`
}


type BibliographicInfo struct {
  XMLName xml.Name `xml:"bibliographicInfo" json:"-"`
  SupplierUniqueRecordId string `xml:"supplierUniqueRecordId,omitempty" json:"supplierUniqueRecordId,omitempty"`
  Title string `xml:"title,omitempty" json:"title,omitempty"`
  Author string `xml:"author,omitempty" json:"author,omitempty"`
  AuthorId string `xml:"authorId,omitempty" json:"authorId,omitempty"`
  Subtitle string `xml:"subtitle,omitempty" json:"subtitle,omitempty"`
  SeriesTitle string `xml:"seriesTitle,omitempty" json:"seriesTitle,omitempty"`
  Edition string `xml:"edition,omitempty" json:"edition,omitempty"`
  TitleOfComponent string `xml:"titleOfComponent,omitempty" json:"titleOfComponent,omitempty"`
  AuthorOfComponent string `xml:"authorOfComponent,omitempty" json:"authorOfComponent,omitempty"`
  Volume []string `xml:"volume,omitempty" json:"volume,omitempty"`
  Issue string `xml:"issue,omitempty" json:"issue,omitempty"`
  PagesRequested string `xml:"pagesRequested,omitempty" json:"pagesRequested,omitempty"`
  EstimatedNoPages string `xml:"estimatedNoPages,omitempty" json:"estimatedNoPages,omitempty"`
  BibliographicItemId []BibliographicItemId `xml:"bibliographicItemId,omitempty" json:"bibliographicItemId,omitempty"`
  Sponsor string `xml:"sponsor,omitempty" json:"sponsor,omitempty"`
  InformationSource string `xml:"informationSource,omitempty" json:"informationSource,omitempty"`
  BibliographicRecordId []BibliographicRecordId `xml:"bibliographicRecordId,omitempty" json:"bibliographicRecordId,omitempty"`
}


type BibliographicRecordId struct {
  XMLName xml.Name `xml:"bibliographicRecordId" json:"-"`
  BibliographicRecordIdentifierCode TypeSchemeValuePair `xml:"bibliographicRecordIdentifierCode" json:"bibliographicRecordIdentifierCode"`
  BibliographicRecordIdentifier string `xml:"bibliographicRecordIdentifier" json:"bibliographicRecordIdentifier"`
}


type BillingInfo struct {
  XMLName xml.Name `xml:"billingInfo" json:"-"`
  PaymentMethod *TypeSchemeValuePair `xml:"paymentMethod,omitempty" json:"paymentMethod,omitempty"`
  MaximumCosts *TypeCosts `xml:"maximumCosts,omitempty" json:"maximumCosts,omitempty"`
  BillingMethod *TypeSchemeValuePair `xml:"billingMethod,omitempty" json:"billingMethod,omitempty"`
  BillingName string `xml:"billingName,omitempty" json:"billingName,omitempty"`
  Address *Address `xml:"address,omitempty" json:"address,omitempty"`
}


type ConfirmationHeader struct {
  XMLName xml.Name `xml:"confirmationHeader" json:"-"`
  SupplyingAgencyId *TypeAgencyId `xml:"supplyingAgencyId,omitempty" json:"supplyingAgencyId,omitempty"`
  RequestingAgencyId *TypeAgencyId `xml:"requestingAgencyId,omitempty" json:"requestingAgencyId,omitempty"`
  Timestamp string `xml:"timestamp" json:"timestamp"`
  RequestingAgencyRequestId string `xml:"requestingAgencyRequestId,omitempty" json:"requestingAgencyRequestId,omitempty"`
  TimestampReceived string `xml:"timestampReceived" json:"timestampReceived"`
  MessageStatus TypeMessageStatus `xml:"messageStatus" json:"messageStatus"`
}

type ConsortialId struct {
  XMLName xml.Name `xml:"consortialId" json:"-"`
  TypeAgencyId
}

type CourierName struct {
  XMLName xml.Name `xml:"courierName" json:"-"`
  TypeSchemeValuePair
}


type DeliveryInfo struct {
  XMLName xml.Name `xml:"deliveryInfo" json:"-"`
  DateSent string `xml:"dateSent" json:"dateSent"`
  ItemId []string `xml:"itemId,omitempty" json:"itemId,omitempty"`
  URL string `xml:"URL,omitempty" json:"URL,omitempty"`
  DeliveryMethod *TypeSchemeValuePair `xml:"deliveryMethod,omitempty" json:"deliveryMethod,omitempty"`
  Address *Address `xml:"address,omitempty" json:"address,omitempty"`
  SentToPatron bool `xml:"sentToPatron,omitempty" json:"sentToPatron,omitempty"`
  LoanCondition []TypeSchemeValuePair `xml:"loanCondition,omitempty" json:"loanCondition,omitempty"`
  ItemFormat *TypeSchemeValuePair `xml:"itemFormat,omitempty" json:"itemFormat,omitempty"`
  ServiceType *TypeServiceType `xml:"serviceType,omitempty" json:"serviceType,omitempty"`
  DeliveryCosts []TypeCosts `xml:"deliveryCosts,omitempty" json:"deliveryCosts,omitempty"`
  PaymentMethod *TypeSchemeValuePair `xml:"paymentMethod,omitempty" json:"paymentMethod,omitempty"`
}

type DeliveryMethod struct {
  XMLName xml.Name `xml:"deliveryMethod" json:"-"`
  TypeSchemeValuePair
}

type Edition struct {
  XMLName xml.Name `xml:"edition" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}


type ElectronicAddress struct {
  XMLName xml.Name `xml:"electronicAddress" json:"-"`
  ElectronicAddressType TypeSchemeValuePair `xml:"electronicAddressType" json:"electronicAddressType"`
  ElectronicAddressData string `xml:"electronicAddressData" json:"electronicAddressData"`
}


type ErrorData struct {
  XMLName xml.Name `xml:"errorData" json:"-"`
  ErrorType TypeErrorType `xml:"errorType" json:"errorType"`
  ErrorValue string `xml:"errorValue,omitempty" json:"errorValue,omitempty"`
}

type ItemFormat struct {
  XMLName xml.Name `xml:"itemFormat" json:"-"`
  TypeSchemeValuePair
}

type LoanCondition struct {
  XMLName xml.Name `xml:"loanCondition" json:"-"`
  TypeSchemeValuePair
}


type MessageInfo struct {
  XMLName xml.Name `xml:"messageInfo" json:"-"`
  ReasonForMessage TypeReasonForMessage `xml:"reasonForMessage" json:"reasonForMessage"`
  AnswerYesNo *TypeYesNo `xml:"answerYesNo,omitempty" json:"answerYesNo,omitempty"`
  Note string `xml:"note,omitempty" json:"note,omitempty"`
  ReasonUnfilled *TypeSchemeValuePair `xml:"reasonUnfilled,omitempty" json:"reasonUnfilled,omitempty"`
  ReasonRetry *TypeSchemeValuePair `xml:"reasonRetry,omitempty" json:"reasonRetry,omitempty"`
}

type MultipleItemRequestId struct {
  XMLName xml.Name `xml:"multipleItemRequestId" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}


type PatronInfo struct {
  XMLName xml.Name `xml:"patronInfo" json:"-"`
  PatronId string `xml:"patronId,omitempty" json:"patronId,omitempty"`
  Surname string `xml:"surname,omitempty" json:"surname,omitempty"`
  GivenName string `xml:"givenName,omitempty" json:"givenName,omitempty"`
  PatronType *TypeSchemeValuePair `xml:"patronType,omitempty" json:"patronType,omitempty"`
  SendToPatron *TypeYesNo `xml:"sendToPatron,omitempty" json:"sendToPatron,omitempty"`
  Address []Address `xml:"address,omitempty" json:"address,omitempty"`
}

type PaymentMethod struct {
  XMLName xml.Name `xml:"paymentMethod" json:"-"`
  TypeSchemeValuePair
}


type PhysicalAddress struct {
  XMLName xml.Name `xml:"physicalAddress" json:"-"`
  Line1 string `xml:"line1,omitempty" json:"line1,omitempty"`
  Line2 string `xml:"line2,omitempty" json:"line2,omitempty"`
  Locality string `xml:"locality,omitempty" json:"locality,omitempty"`
  PostalCode string `xml:"postalCode,omitempty" json:"postalCode,omitempty"`
  Region string `xml:"region,omitempty" json:"region,omitempty"`
  Country *TypeSchemeValuePair `xml:"country,omitempty" json:"country,omitempty"`
  //  ISO 3166-1 
}


type PublicationInfo struct {
  XMLName xml.Name `xml:"publicationInfo" json:"-"`
  Publisher string `xml:"publisher,omitempty" json:"publisher,omitempty"`
  PublisherId string `xml:"publisherId,omitempty" json:"publisherId,omitempty"`
  //  ISNI ISO-27729 
  PublicationType *TypeSchemeValuePair `xml:"publicationType,omitempty" json:"publicationType,omitempty"`
  PublicationDate string `xml:"publicationDate,omitempty" json:"publicationDate,omitempty"`
  PlaceOfPublication string `xml:"placeOfPublication,omitempty" json:"placeOfPublication,omitempty"`
}


type RequestedDeliveryInfo struct {
  XMLName xml.Name `xml:"requestedDeliveryInfo" json:"-"`
  SortOrder *SortOrder `xml:"sortOrder,omitempty" json:"sortOrder,omitempty"`
  Address *Address `xml:"address,omitempty" json:"address,omitempty"`
  DeliveryMethod *TypeSchemeValuePair `xml:"deliveryMethod,omitempty" json:"deliveryMethod,omitempty"`
  CourierName *TypeSchemeValuePair `xml:"courierName,omitempty" json:"courierName,omitempty"`
}

type TypeRequestHeader struct {
  SupplyingAgencyId *TypeAgencyId `xml:"supplyingAgencyId,omitempty" json:"supplyingAgencyId,omitempty"`
  RequestingAgencyId TypeAgencyId `xml:"requestingAgencyId" json:"requestingAgencyId"`
  ConsortialId *TypeAgencyId `xml:"consortialId,omitempty" json:"consortialId,omitempty"`
  MultipleItemRequestId string `xml:"multipleItemRequestId,omitempty" json:"multipleItemRequestId,omitempty"`
  Timestamp string `xml:"timestamp" json:"timestamp"`
  RequestingAgencyRequestId string `xml:"requestingAgencyRequestId" json:"requestingAgencyRequestId"`
  RequestingAgencyAuthentication *RequestingAgencyAuthentication `xml:"requestingAgencyAuthentication,omitempty" json:"requestingAgencyAuthentication,omitempty"`
}


type RequestingAgencyAuthentication struct {
  XMLName xml.Name `xml:"requestingAgencyAuthentication" json:"-"`
  AccountId string `xml:"accountId,omitempty" json:"accountId,omitempty"`
  SecurityCode string `xml:"securityCode,omitempty" json:"securityCode,omitempty"`
}

type RequestingAgencyId struct {
  XMLName xml.Name `xml:"requestingAgencyId" json:"-"`
  TypeAgencyId
}


type RequestingAgencyInfo struct {
  XMLName xml.Name `xml:"requestingAgencyInfo" json:"-"`
  Name string `xml:"name,omitempty" json:"name,omitempty"`
  ContactName string `xml:"contactName,omitempty" json:"contactName,omitempty"`
  Address []Address `xml:"address,omitempty" json:"address,omitempty"`
}

type TypeRequestingAgencyMessageHeader struct {
  SupplyingAgencyId TypeAgencyId `xml:"supplyingAgencyId" json:"supplyingAgencyId"`
  RequestingAgencyId TypeAgencyId `xml:"requestingAgencyId" json:"requestingAgencyId"`
  ConsortialId *TypeAgencyId `xml:"consortialId,omitempty" json:"consortialId,omitempty"`
  Timestamp string `xml:"timestamp" json:"timestamp"`
  RequestingAgencyRequestId string `xml:"requestingAgencyRequestId" json:"requestingAgencyRequestId"`
  SupplyingAgencyRequestId string `xml:"supplyingAgencyRequestId,omitempty" json:"supplyingAgencyRequestId,omitempty"`
  RequestingAgencyAuthentication *RequestingAgencyAuthentication `xml:"requestingAgencyAuthentication,omitempty" json:"requestingAgencyAuthentication,omitempty"`
}

type RequestingAgencyRequestId struct {
  XMLName xml.Name `xml:"requestingAgencyRequestId" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}


type ReturnInfo struct {
  XMLName xml.Name `xml:"returnInfo" json:"-"`
  ReturnAgencyId *TypeAgencyId `xml:"returnAgencyId,omitempty" json:"returnAgencyId,omitempty"`
  Name string `xml:"name,omitempty" json:"name,omitempty"`
  PhysicalAddress *PhysicalAddress `xml:"physicalAddress,omitempty" json:"physicalAddress,omitempty"`
}


type RetryInfo struct {
  XMLName xml.Name `xml:"retryInfo" json:"-"`
  LoanCondition []TypeSchemeValuePair `xml:"loanCondition,omitempty" json:"loanCondition,omitempty"`
  Edition []string `xml:"edition,omitempty" json:"edition,omitempty"`
  ItemFormat []TypeSchemeValuePair `xml:"itemFormat,omitempty" json:"itemFormat,omitempty"`
  Volume []string `xml:"volume,omitempty" json:"volume,omitempty"`
  ServiceType *TypeServiceType `xml:"serviceType,omitempty" json:"serviceType,omitempty"`
  ServiceLevel []TypeSchemeValuePair `xml:"serviceLevel,omitempty" json:"serviceLevel,omitempty"`
  DeliveryMethod []TypeSchemeValuePair `xml:"deliveryMethod,omitempty" json:"deliveryMethod,omitempty"`
  CourierName []TypeSchemeValuePair `xml:"courierName,omitempty" json:"courierName,omitempty"`
  OfferedCosts []TypeCosts `xml:"offeredCosts,omitempty" json:"offeredCosts,omitempty"`
  PaymentMethod []TypeSchemeValuePair `xml:"paymentMethod,omitempty" json:"paymentMethod,omitempty"`
  RetryBefore string `xml:"retryBefore,omitempty" json:"retryBefore,omitempty"`
  RetryAfter string `xml:"retryAfter,omitempty" json:"retryAfter,omitempty"`
}


type ServiceInfo struct {
  XMLName xml.Name `xml:"serviceInfo" json:"-"`
  RequestType *TypeRequestType `xml:"requestType,omitempty" json:"requestType,omitempty"`
  RequestSubType []TypeRequestSubType `xml:"requestSubType,omitempty" json:"requestSubType,omitempty"`
  RequestingAgencyPreviousRequestId string `xml:"requestingAgencyPreviousRequestId,omitempty" json:"requestingAgencyPreviousRequestId,omitempty"`
  ServiceType TypeServiceType `xml:"serviceType" json:"serviceType"`
  ServiceLevel *TypeSchemeValuePair `xml:"serviceLevel,omitempty" json:"serviceLevel,omitempty"`
  ItemFormat *TypeSchemeValuePair `xml:"itemFormat,omitempty" json:"itemFormat,omitempty"`
  NeedBeforeDate string `xml:"needBeforeDate,omitempty" json:"needBeforeDate,omitempty"`
  CopyrightCompliance *TypeSchemeValuePair `xml:"copyrightCompliance,omitempty" json:"copyrightCompliance,omitempty"`
  AnyEdition *TypeYesNo `xml:"anyEdition,omitempty" json:"anyEdition,omitempty"`
  //  Deprecated 
  PreferredEdition *TypePreferredEdition `xml:"preferredEdition,omitempty" json:"preferredEdition,omitempty"`
  //  Recommended 
  LoanCondition []TypeSchemeValuePair `xml:"loanCondition,omitempty" json:"loanCondition,omitempty"`
  StartDate string `xml:"startDate,omitempty" json:"startDate,omitempty"`
  EndDate string `xml:"endDate,omitempty" json:"endDate,omitempty"`
  Note string `xml:"note,omitempty" json:"note,omitempty"`
}

type ServiceLevel struct {
  XMLName xml.Name `xml:"serviceLevel" json:"-"`
  TypeSchemeValuePair
}


type ShippingInfo struct {
  XMLName xml.Name `xml:"shippingInfo" json:"-"`
  CourierName *TypeSchemeValuePair `xml:"courierName,omitempty" json:"courierName,omitempty"`
  TrackingId []string `xml:"trackingId,omitempty" json:"trackingId,omitempty"`
  Insurance *TypeYesNo `xml:"insurance,omitempty" json:"insurance,omitempty"`
  InsuranceThirdParty *TypeYesNo `xml:"insuranceThirdParty,omitempty" json:"insuranceThirdParty,omitempty"`
  ThirdPartyName string `xml:"thirdPartyName,omitempty" json:"thirdPartyName,omitempty"`
  InsuranceCosts []TypeCosts `xml:"insuranceCosts,omitempty" json:"insuranceCosts,omitempty"`
}


type SortOrder int64



type StatusInfo struct {
  XMLName xml.Name `xml:"statusInfo" json:"-"`
  Status TypeStatus `xml:"status" json:"status"`
  ExpectedDeliveryDate string `xml:"expectedDeliveryDate,omitempty" json:"expectedDeliveryDate,omitempty"`
  DueDate string `xml:"dueDate,omitempty" json:"dueDate,omitempty"`
  LastChange string `xml:"lastChange" json:"lastChange"`
}


type SupplierInfo struct {
  XMLName xml.Name `xml:"supplierInfo" json:"-"`
  SortOrder *SortOrder `xml:"sortOrder,omitempty" json:"sortOrder,omitempty"`
  SupplierCode *TypeAgencyId `xml:"supplierCode,omitempty" json:"supplierCode,omitempty"`
  SupplierDescription string `xml:"supplierDescription,omitempty" json:"supplierDescription,omitempty"`
  BibliographicRecordId *BibliographicRecordId `xml:"bibliographicRecordId,omitempty" json:"bibliographicRecordId,omitempty"`
  CallNumber string `xml:"callNumber,omitempty" json:"callNumber,omitempty"`
  SummaryHoldings string `xml:"summaryHoldings,omitempty" json:"summaryHoldings,omitempty"`
  AvailabilityNote string `xml:"availabilityNote,omitempty" json:"availabilityNote,omitempty"`
}

type SupplyingAgencyId struct {
  XMLName xml.Name `xml:"supplyingAgencyId" json:"-"`
  TypeAgencyId
}

type TypeSupplyingAgencyMessageHeader struct {
  SupplyingAgencyId TypeAgencyId `xml:"supplyingAgencyId" json:"supplyingAgencyId"`
  RequestingAgencyId TypeAgencyId `xml:"requestingAgencyId" json:"requestingAgencyId"`
  Timestamp string `xml:"timestamp" json:"timestamp"`
  RequestingAgencyRequestId string `xml:"requestingAgencyRequestId" json:"requestingAgencyRequestId"`
  SupplyingAgencyRequestId string `xml:"supplyingAgencyRequestId,omitempty" json:"supplyingAgencyRequestId,omitempty"`
}

type SupplyingAgencyRequestId struct {
  XMLName xml.Name `xml:"supplyingAgencyRequestId" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Timestamp struct {
  XMLName xml.Name `xml:"timestamp" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type TimestampReceived struct {
  XMLName xml.Name `xml:"timestampReceived" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Volume struct {
  XMLName xml.Name `xml:"volume" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type TypeAgencyId struct {
  AgencyIdType TypeSchemeValuePair `xml:"agencyIdType" json:"agencyIdType"`
  AgencyIdValue string `xml:"agencyIdValue" json:"agencyIdValue"`
}

type TypeCosts struct {
  CurrencyCode TypeSchemeValuePair `xml:"currencyCode" json:"currencyCode"`
  // ISO 4217 
  MonetaryValue float64 `xml:"monetaryValue" json:"monetaryValue"`
}

type TypeSchemeValuePair struct {
  Text string `xml:",chardata" json:"#text,omitempty"`
  Scheme *utils.PrefixAttr `xml:"scheme,attr,omitempty" json:"@scheme,omitempty"`
}

type TypeAction string

const TypeActionStatusRequest TypeAction = "StatusRequest"
const TypeActionReceived TypeAction = "Received"
const TypeActionCancel TypeAction = "Cancel"
const TypeActionRenew TypeAction = "Renew"
const TypeActionHoldReturn TypeAction = "HoldReturn"
const TypeActionShippedReturn TypeAction = "ShippedReturn"
const TypeActionShippedForward TypeAction = "ShippedForward"
const TypeActionNotification TypeAction = "Notification"
const TypeActionLost TypeAction = "Lost"

type TypeErrorType string

const TypeErrorTypeUnsupportedActionType TypeErrorType = "UnsupportedActionType"
const TypeErrorTypeUnsupportedReasonForMessageType TypeErrorType = "UnsupportedReasonForMessageType"
const TypeErrorTypeUnrecognisedDataElement TypeErrorType = "UnrecognisedDataElement"
const TypeErrorTypeUnrecognisedDataValue TypeErrorType = "UnrecognisedDataValue"
const TypeErrorTypeBadlyFormedMessage TypeErrorType = "BadlyFormedMessage"

type TypeMessageStatus string

const TypeMessageStatusOK TypeMessageStatus = "OK"
const TypeMessageStatusERROR TypeMessageStatus = "ERROR"

type TypePreferredEdition string

const TypePreferredEditionMostRecentEdition TypePreferredEdition = "MostRecentEdition"
const TypePreferredEditionThisEdition TypePreferredEdition = "ThisEdition"
const TypePreferredEditionAnyEdition TypePreferredEdition = "AnyEdition"

type TypeReasonForMessage string

const TypeReasonForMessageRequestResponse TypeReasonForMessage = "RequestResponse"
const TypeReasonForMessageStatusRequestResponse TypeReasonForMessage = "StatusRequestResponse"
const TypeReasonForMessageRenewResponse TypeReasonForMessage = "RenewResponse"
const TypeReasonForMessageCancelResponse TypeReasonForMessage = "CancelResponse"
const TypeReasonForMessageStatusChange TypeReasonForMessage = "StatusChange"
const TypeReasonForMessageNotification TypeReasonForMessage = "Notification"

type TypeRequestType string

const TypeRequestTypeNew TypeRequestType = "New"
const TypeRequestTypeRetry TypeRequestType = "Retry"
const TypeRequestTypeReminder TypeRequestType = "Reminder"

type TypeRequestSubType string

const TypeRequestSubTypeBookingRequest TypeRequestSubType = "BookingRequest"
const TypeRequestSubTypeMultipleItemRequest TypeRequestSubType = "MultipleItemRequest"
const TypeRequestSubTypePatronRequest TypeRequestSubType = "PatronRequest"
const TypeRequestSubTypeTransferRequest TypeRequestSubType = "TransferRequest"
const TypeRequestSubTypeSupplyingLibrarysChoice TypeRequestSubType = "SupplyingLibrarysChoice"

type TypeServiceType string

const TypeServiceTypeCopy TypeServiceType = "Copy"
const TypeServiceTypeLoan TypeServiceType = "Loan"
const TypeServiceTypeCopyOrLoan TypeServiceType = "CopyOrLoan"

type TypeStatus string

const TypeStatusRequestReceived TypeStatus = "RequestReceived"
const TypeStatusExpectToSupply TypeStatus = "ExpectToSupply"
const TypeStatusWillSupply TypeStatus = "WillSupply"
const TypeStatusLoaned TypeStatus = "Loaned"
const TypeStatusOverdue TypeStatus = "Overdue"
const TypeStatusRecalled TypeStatus = "Recalled"
const TypeStatusRetryPossible TypeStatus = "RetryPossible"
const TypeStatusUnfilled TypeStatus = "Unfilled"
const TypeStatusHoldReturn TypeStatus = "HoldReturn"
const TypeStatusReleaseHoldReturn TypeStatus = "ReleaseHoldReturn"
const TypeStatusCopyCompleted TypeStatus = "CopyCompleted"
const TypeStatusLoanCompleted TypeStatus = "LoanCompleted"
const TypeStatusCompletedWithoutReturn TypeStatus = "CompletedWithoutReturn"
const TypeStatusCancelled TypeStatus = "Cancelled"

type TypeYesNo string

const TypeYesNoY TypeYesNo = "Y"
const TypeYesNoN TypeYesNo = "N"

