// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

// OPAC XML. This is the XML that YAZ is using to represent Z39.50 OPAC
// records.
package schema

import (
  "encoding/xml"
)


type OpacRecord struct {
  XMLName xml.Name `xml:"opacRecord"`
  BibliographicRecord struct { XMLContent []byte `xml:",innerxml"` } `xml:"bibliographicRecord"`
  Holdings struct {
    XMLName xml.Name `xml:"holdings"`
    Holding []Holding `xml:"holding,omitempty"`
  }
}


type Holding struct {
  XMLName xml.Name `xml:"holding"`
  TypeOfRecord string `xml:"typeOfRecord,omitempty"`
  EncodingLevel string `xml:"encodingLevel,omitempty"`
  Format string `xml:"format,omitempty"`
  ReceiptAcqStatus string `xml:"receiptAcqStatus,omitempty"`
  GeneralRetention string `xml:"generalRetention,omitempty"`
  Completeness string `xml:"completeness,omitempty"`
  DateOfReport string `xml:"dateOfReport,omitempty"`
  NucCode string `xml:"nucCode,omitempty"`
  LocalLocation string `xml:"localLocation,omitempty"`
  ShelvingLocation string `xml:"shelvingLocation,omitempty"`
  CallNumber string `xml:"callNumber,omitempty"`
  ShelvingData string `xml:"shelvingData,omitempty"`
  CopyNumber string `xml:"copyNumber,omitempty"`
  PublicNote string `xml:"publicNote,omitempty"`
  ReproductionNote string `xml:"reproductionNote,omitempty"`
  TermsUseRepro string `xml:"termsUseRepro,omitempty"`
  EnumAndChron string `xml:"enumAndChron,omitempty"`
  Volumes *Volumes `xml:"volumes,omitempty"`
  Circulations *Circulations `xml:"circulations,omitempty"`
}


type Volume struct {
  XMLName xml.Name `xml:"volume"`
  Enumeration string `xml:"enumeration,omitempty"`
  Chronology string `xml:"chronology,omitempty"`
  EnumAndChron string `xml:"enumAndChron,omitempty"`
}


type Circulation struct {
  XMLName xml.Name `xml:"circulation"`
  AvailableNow struct {
    XMLName xml.Name `xml:"availableNow"`
    Value string `xml:"value,attr"`
  }
  AvailabilityDate string `xml:"availabilityDate,omitempty"`
  AvailableThru string `xml:"availableThru,omitempty"`
  Restrictions string `xml:"restrictions,omitempty"`
  ItemId string `xml:"itemId,omitempty"`
  Renewable struct {
    XMLName xml.Name `xml:"renewable"`
    Value string `xml:"value,attr"`
  }
  OnHold struct {
    XMLName xml.Name `xml:"onHold"`
    Value string `xml:"value,attr"`
  }
  EnumAndChron *struct { XMLContent []byte `xml:",innerxml"` } `xml:"enumAndChron,omitempty"`
  Midspine *struct { XMLContent []byte `xml:",innerxml"` } `xml:"midspine,omitempty"`
  TemporaryLocation *struct { XMLContent []byte `xml:",innerxml"` } `xml:"temporaryLocation,omitempty"`
}


type Volumes struct {
  XMLName xml.Name `xml:"volumes"`
  Volume []Volume `xml:"volume,omitempty"`
}


type Circulations struct {
  XMLName xml.Name `xml:"circulations"`
  Circulation []Circulation `xml:"circulation,omitempty"`
}

