// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

// OPAC XML. This is the XML that YAZ is using to represent Z39.50 OPAC
// records.
package schema

import (
  "encoding/xml"
)


type OpacRecord struct {
  XMLName xml.Name `xml:"opacRecord" json:"-"`
  BibliographicRecord struct { XMLContent []byte `xml:",innerxml" json:"#content"` } `xml:"bibliographicRecord" json:"bibliographicRecord"`
  Holdings struct {
    XMLName xml.Name `xml:"holdings" json:"-"`
    Holding []Holding `xml:"holding,omitempty" json:"holding,omitempty"`
  }
}


type Holding struct {
  XMLName xml.Name `xml:"holding" json:"-"`
  TypeOfRecord string `xml:"typeOfRecord,omitempty" json:"typeOfRecord,omitempty"`
  EncodingLevel string `xml:"encodingLevel,omitempty" json:"encodingLevel,omitempty"`
  Format string `xml:"format,omitempty" json:"format,omitempty"`
  ReceiptAcqStatus string `xml:"receiptAcqStatus,omitempty" json:"receiptAcqStatus,omitempty"`
  GeneralRetention string `xml:"generalRetention,omitempty" json:"generalRetention,omitempty"`
  Completeness string `xml:"completeness,omitempty" json:"completeness,omitempty"`
  DateOfReport string `xml:"dateOfReport,omitempty" json:"dateOfReport,omitempty"`
  NucCode string `xml:"nucCode,omitempty" json:"nucCode,omitempty"`
  LocalLocation string `xml:"localLocation,omitempty" json:"localLocation,omitempty"`
  ShelvingLocation string `xml:"shelvingLocation,omitempty" json:"shelvingLocation,omitempty"`
  CallNumber string `xml:"callNumber,omitempty" json:"callNumber,omitempty"`
  ShelvingData string `xml:"shelvingData,omitempty" json:"shelvingData,omitempty"`
  CopyNumber string `xml:"copyNumber,omitempty" json:"copyNumber,omitempty"`
  PublicNote string `xml:"publicNote,omitempty" json:"publicNote,omitempty"`
  ReproductionNote string `xml:"reproductionNote,omitempty" json:"reproductionNote,omitempty"`
  TermsUseRepro string `xml:"termsUseRepro,omitempty" json:"termsUseRepro,omitempty"`
  EnumAndChron string `xml:"enumAndChron,omitempty" json:"enumAndChron,omitempty"`
  Volumes *Volumes `xml:"volumes,omitempty" json:"volumes,omitempty"`
  Circulations *Circulations `xml:"circulations,omitempty" json:"circulations,omitempty"`
}


type Volume struct {
  XMLName xml.Name `xml:"volume" json:"-"`
  Enumeration string `xml:"enumeration,omitempty" json:"enumeration,omitempty"`
  Chronology string `xml:"chronology,omitempty" json:"chronology,omitempty"`
  EnumAndChron string `xml:"enumAndChron,omitempty" json:"enumAndChron,omitempty"`
}


type Circulation struct {
  XMLName xml.Name `xml:"circulation" json:"-"`
  AvailableNow struct {
    XMLName xml.Name `xml:"availableNow" json:"-"`
    Value string `xml:"value,attr" json:"@value"`
  }
  AvailabilityDate string `xml:"availabilityDate,omitempty" json:"availabilityDate,omitempty"`
  AvailableThru string `xml:"availableThru,omitempty" json:"availableThru,omitempty"`
  Restrictions string `xml:"restrictions,omitempty" json:"restrictions,omitempty"`
  ItemId string `xml:"itemId,omitempty" json:"itemId,omitempty"`
  Renewable struct {
    XMLName xml.Name `xml:"renewable" json:"-"`
    Value string `xml:"value,attr" json:"@value"`
  }
  OnHold struct {
    XMLName xml.Name `xml:"onHold" json:"-"`
    Value string `xml:"value,attr" json:"@value"`
  }
  EnumAndChron *struct { XMLContent []byte `xml:",innerxml" json:"#content"` } `xml:"enumAndChron,omitempty" json:"enumAndChron,omitempty"`
  Midspine *struct { XMLContent []byte `xml:",innerxml" json:"#content"` } `xml:"midspine,omitempty" json:"midspine,omitempty"`
  TemporaryLocation *struct { XMLContent []byte `xml:",innerxml" json:"#content"` } `xml:"temporaryLocation,omitempty" json:"temporaryLocation,omitempty"`
}


type Volumes struct {
  XMLName xml.Name `xml:"volumes" json:"-"`
  Volume []Volume `xml:"volume,omitempty" json:"volume,omitempty"`
}


type Circulations struct {
  XMLName xml.Name `xml:"circulations" json:"-"`
  Circulation []Circulation `xml:"circulation,omitempty" json:"circulation,omitempty"`
}

