// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

package PurchaseOrderSchema

import (
  "encoding/xml"
)

type Comment struct {
  XMLName xml.Name `xml:"comment"`
  Text string `xml:",chardata"`
}

type PurchaseOrder struct {
  XMLName xml.Name `xml:"purchaseOrder"`
  PurchaseOrderType
}

type USAddress struct {
  //         Purchase order schema for Example.Microsoft.com.
  //       
  Name string `xml:"name"`
  Street string `xml:"street"`
  City string `xml:"city"`
  State string `xml:"state"`
  Zip float64 `xml:"zip"`
  Country string `xml:"country,attr,omitempty"`
}

type SKU string


type Items struct {
  Item []Item `xml:"item,omitempty"`
}

type PurchaseOrderType struct {
  ShipTo USAddress `xml:"shipTo"`
  BillTo USAddress `xml:"billTo"`
  Comment string `xml:"comment,omitempty"`
  Items Items `xml:"items"`
  OrderDate string `xml:"orderDate,attr,omitempty"`
  ConfirmDate string `xml:"confirmDate,attr"`
}


type Item struct {
  XMLName xml.Name `xml:"item"`
  ProductName string `xml:"productName"`
  Quantity uint64 `xml:"quantity"`
  USPrice float64 `xml:"USPrice"`
  Comment string `xml:"comment"`
  ShipDate string `xml:"shipDate,omitempty"`
  PartNum string `xml:"partNum,attr,omitempty"`
}

