// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package searchResultAnalysis

import (
  "encoding/xml"
)

type SearchResultAnalysis struct {
  XMLName xml.Name `xml:"searchResultAnalysis" json:"-"`
  SearchResultAnalysisDefinition
}

type SearchResultAnalysisDefinition struct {
  Datasource []DatasourceDefinition `xml:"datasource,omitempty" json:"datasource,omitempty"`
  SubqueryResult []SubqueryResultDefinition `xml:"subqueryResult,omitempty" json:"subqueryResult,omitempty"`
}

type DatasourceDefinition struct {
  DatasourceDisplayLabel string `xml:"datasourceDisplayLabel,omitempty" json:"datasourceDisplayLabel,omitempty"`
  DatasourceDescription string `xml:"datasourceDescription,omitempty" json:"datasourceDescription,omitempty"`
  BaseURL string `xml:"baseURL,omitempty" json:"baseURL,omitempty"`
  SubqueryResults SubqueryResultsDefinition `xml:"subqueryResults" json:"subqueryResults"`
  Full string `xml:"full,attr,omitempty" json:"@full,omitempty"`
}

type SubqueryResultsDefinition struct {
  SubqueryResult []SubqueryResultDefinition `xml:"subqueryResult,omitempty" json:"subqueryResult,omitempty"`
}

type SubqueryResultDefinition struct {
  SubqueryDisplayLabel string `xml:"subqueryDisplayLabel,omitempty" json:"subqueryDisplayLabel,omitempty"`
  Subquery string `xml:"subquery" json:"subquery"`
  Count int64 `xml:"count" json:"count"`
  RequestUrl string `xml:"requestUrl,omitempty" json:"requestUrl,omitempty"`
  Full string `xml:"full,attr,omitempty" json:"@full,omitempty"`
}

type FullDefinition string

const FullDefinitionTrue FullDefinition = "true"

type BaseURL struct {
  XMLName xml.Name `xml:"baseURL" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Count struct {
  XMLName xml.Name `xml:"count" json:"-"`
  Text int64 `xml:",chardata" json:"#text,omitempty"`
}

type Datasource struct {
  XMLName xml.Name `xml:"datasource" json:"-"`
  DatasourceDefinition
}

type DatasourceDescription struct {
  XMLName xml.Name `xml:"datasourceDescription" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type DatasourceDisplayLabel struct {
  XMLName xml.Name `xml:"datasourceDisplayLabel" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type RequestUrl struct {
  XMLName xml.Name `xml:"requestUrl" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Subquery struct {
  XMLName xml.Name `xml:"subquery" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type SubqueryDisplayLabel struct {
  XMLName xml.Name `xml:"subqueryDisplayLabel" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type SubqueryResult struct {
  XMLName xml.Name `xml:"subqueryResult" json:"-"`
  SubqueryResultDefinition
}

type SubqueryResults struct {
  XMLName xml.Name `xml:"subqueryResults" json:"-"`
  SubqueryResultsDefinition
}

