// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package sruResponse

import (
  "encoding/xml"
  diag "github.com/indexdata/xsd2goxsl/xsd/diagnostic.xsd_test"
  facet "github.com/indexdata/xsd2goxsl/xsd/facetedResults.xsd_test"
  sra "github.com/indexdata/xsd2goxsl/xsd/searchResultAnalysis.xsd_test"
  xcql "github.com/indexdata/xsd2goxsl/xsd/xcql.xsd_test"
  scan "github.com/indexdata/xsd2goxsl/xsd/scan.xsd_test"
)

type SearchRetrieveResponse struct {
  XMLName xml.Name `xml:"searchRetrieveResponse" json:"-"`
  SearchRetrieveResponseDefinition
}

type ExplainResponse struct {
  XMLName xml.Name `xml:"explainResponse" json:"-"`
  ExplainResponseDefinition
}

type ScanResponse struct {
  XMLName xml.Name `xml:"scanResponse" json:"-"`
  scan.ScanResponseDefinition
}

type SearchRetrieveResponseDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty" json:"version,omitempty"`
  //  ******
  //                       version is for use in version 1.2 or earlier. It is removed in version 2.0.
  //                   ******
  NumberOfRecords uint64 `xml:"numberOfRecords,omitempty" json:"numberOfRecords,omitempty"`
  ResultSetId string `xml:"resultSetId,omitempty" json:"resultSetId,omitempty"`
  ResultSetIdleTime uint64 `xml:"resultSetIdleTime,omitempty" json:"resultSetIdleTime,omitempty"`
  //                       resultSetIdleTime is for use in version 1.2 or earlier. It is removed in version 2.0.
  Records *RecordsDefinition `xml:"records,omitempty" json:"records,omitempty"`
  NextRecordPosition uint64 `xml:"nextRecordPosition,omitempty" json:"nextRecordPosition,omitempty"`
  EchoedSearchRetrieveRequest *EchoedSearchRetrieveRequestDefinition `xml:"echoedSearchRetrieveRequest,omitempty" json:"echoedSearchRetrieveRequest,omitempty"`
  Diagnostics *DiagnosticsDefinition `xml:"diagnostics,omitempty" json:"diagnostics,omitempty"`
  ExtraResponseData []ExtensionDefinition `xml:"extraResponseData,omitempty" json:"extraResponseData,omitempty"`
  //  ****
  // the following are new in version 2. They may not be used in version 1.2 or earlier.
  //                  
  XMLContent []byte   `xml:",innerxml" json:"#content"`
  ResultSetTTL uint64 `xml:"resultSetTTL,omitempty" json:"resultSetTTL,omitempty"`
  //                       resultSetTTL replaces resultSetIdleTime in version 2.0.
  ResultCountPrecision []string `xml:"resultCountPrecision,omitempty" json:"resultCountPrecision,omitempty"`
  FacetedResults []facet.FacetedResultsDefinition `xml:"facetedResults,omitempty" json:"facetedResults,omitempty"`
  SearchResultAnalysis []sra.SearchResultAnalysisDefinition `xml:"searchResultAnalysis,omitempty" json:"searchResultAnalysis,omitempty"`
}

type ExplainResponseDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty" json:"version,omitempty"`
  Record RecordDefinition `xml:"record" json:"record"`
  EchoedExplainRequest *EchoedExplainRequestDefinition `xml:"echoedExplainRequest,omitempty" json:"echoedExplainRequest,omitempty"`
  Diagnostics *DiagnosticsDefinition `xml:"diagnostics,omitempty" json:"diagnostics,omitempty"`
  ExtraResponseData *ExtensionDefinition `xml:"extraResponseData,omitempty" json:"extraResponseData,omitempty"`
}

type DiagnosticsDefinition struct {
  Diagnostic []diag.Diagnostic `xml:"diagnostic,omitempty" json:"diagnostic,omitempty"`
}

type EchoedExplainRequestDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty" json:"version,omitempty"`
  RecordXMLEscaping *RecordXMLEscapingDefinition `xml:"recordXMLEscaping,omitempty" json:"recordXMLEscaping,omitempty"`
  RecordPacking string `xml:"recordPacking,omitempty" json:"recordPacking,omitempty"`
  Stylesheet string `xml:"stylesheet,omitempty" json:"stylesheet,omitempty"`
  ExtraRequestData *ExtensionDefinition `xml:"extraRequestData,omitempty" json:"extraRequestData,omitempty"`
}

type EchoedSearchRetrieveRequestDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty" json:"version,omitempty"`
  QueryType string `xml:"queryType,omitempty" json:"queryType,omitempty"`
  Query string `xml:"query,omitempty" json:"query,omitempty"`
  XQuery []xcql.XcqlDefinition `xml:"xQuery,omitempty" json:"xQuery,omitempty"`
  //  "query" is a string representation, and xQuery is a structured (e.g. XML) representation, of the query 
  StartRecord uint64 `xml:"startRecord,omitempty" json:"startRecord,omitempty"`
  MaximumRecords uint64 `xml:"maximumRecords,omitempty" json:"maximumRecords,omitempty"`
  RecordXMLEscaping *RecordXMLEscapingDefinition `xml:"recordXMLEscaping,omitempty" json:"recordXMLEscaping,omitempty"`
  RecordPacking string `xml:"recordPacking,omitempty" json:"recordPacking,omitempty"`
  RecordSchema string `xml:"recordSchema,omitempty" json:"recordSchema,omitempty"`
  FacetParameters string `xml:"facetParameters,omitempty" json:"facetParameters,omitempty"`
  //  one or more strings of form "[facetParameter]=value"  where [facetParameter] is one of the facet parameters
  ResultSetTTL uint64 `xml:"resultSetTTL,omitempty" json:"resultSetTTL,omitempty"`
  SortKeys string `xml:"sortKeys,omitempty" json:"sortKeys,omitempty"`
  XSortKeys []XSortKeysDefinition `xml:"xSortKeys,omitempty" json:"xSortKeys,omitempty"`
  // "sortKeys" is a string representation, and xsortKeys is a structured (e.g. XML) representation, of the sort keys
  Stylesheet string `xml:"stylesheet,omitempty" json:"stylesheet,omitempty"`
  RenderedBy *RenderedByDefinition `xml:"renderedBy,omitempty" json:"renderedBy,omitempty"`
  ExtraRequestParameter []string `xml:"extraRequestParameter,omitempty" json:"extraRequestParameter,omitempty"`
  HttpAccept []string `xml:"httpAccept,omitempty" json:"httpAccept,omitempty"`
  ResponseType string `xml:"responseType,omitempty" json:"responseType,omitempty"`
}

type ExtensionDefinition struct {
  XMLContent []byte   `xml:",innerxml" json:"#content"`
}

type RecordDefinition struct {
  RecordSchema string `xml:"recordSchema" json:"recordSchema"`
  RecordPacking string `xml:"recordPacking,omitempty" json:"recordPacking,omitempty"`
  //         recordPacking has different meaning when used for versions 1.2 or earlier than for 2.0 or later.
  //              
  RecordXMLEscaping *RecordXMLEscapingDefinition `xml:"recordXMLEscaping,omitempty" json:"recordXMLEscaping,omitempty"`
  // 				recordXMLEscaping  valid only for 2.0 or later.
  //   
  RecordData StringOrXmlFragmentDefinition `xml:"recordData" json:"recordData"`
  RecordPosition uint64 `xml:"recordPosition,omitempty" json:"recordPosition,omitempty"`
  ExtraRecordData *ExtensionDefinition `xml:"extraRecordData,omitempty" json:"extraRecordData,omitempty"`
  XMLContent []byte   `xml:",innerxml" json:"#content"`
}

type RecordXMLEscapingDefinition string

const RecordXMLEscapingDefinitionString RecordXMLEscapingDefinition = "string"
const RecordXMLEscapingDefinitionXml RecordXMLEscapingDefinition = "xml"

type RecordsDefinition struct {
  Record []RecordDefinition `xml:"record,omitempty" json:"record,omitempty"`
}

type RenderedByDefinition string

const RenderedByDefinitionClient RenderedByDefinition = "client"
const RenderedByDefinitionServer RenderedByDefinition = "server"

type SortKeyDefinition struct {
  Path string `xml:"path" json:"path"`
  Schema string `xml:"schema,omitempty" json:"schema,omitempty"`
  Ascending bool `xml:"ascending,omitempty" json:"ascending,omitempty"`
  CaseSensitive bool `xml:"caseSensitive,omitempty" json:"caseSensitive,omitempty"`
  MissingValue string `xml:"missingValue,omitempty" json:"missingValue,omitempty"`
}

type StringOrXmlFragmentDefinition struct {
  XMLContent []byte   `xml:",innerxml" json:"#content"`
}

type XSortKeysDefinition struct {
  SortKey []SortKeyDefinition `xml:"sortKey,omitempty" json:"sortKey,omitempty"`
}

type VersionDefinition string

const VersionDefinition1_0 VersionDefinition = "1.0"
const VersionDefinition1_1 VersionDefinition = "1.1"
const VersionDefinition1_2 VersionDefinition = "1.2"
const VersionDefinition2_0 VersionDefinition = "2.0"

type Ascending struct {
  XMLName xml.Name `xml:"ascending" json:"-"`
  Text bool `xml:",chardata" json:"#text,omitempty"`
}

type CaseSensitive struct {
  XMLName xml.Name `xml:"caseSensitive" json:"-"`
  Text bool `xml:",chardata" json:"#text,omitempty"`
}

type Diagnostics struct {
  XMLName xml.Name `xml:"diagnostics" json:"-"`
  DiagnosticsDefinition
}

type DisplayTerm struct {
  XMLName xml.Name `xml:"displayTerm" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type EchoedExplainRequest struct {
  XMLName xml.Name `xml:"echoedExplainRequest" json:"-"`
  EchoedExplainRequestDefinition
}

type EchoedSearchRetrieveRequest struct {
  XMLName xml.Name `xml:"echoedSearchRetrieveRequest" json:"-"`
  EchoedSearchRetrieveRequestDefinition
}

type ExtraRecordData struct {
  XMLName xml.Name `xml:"extraRecordData" json:"-"`
  ExtensionDefinition
}

type ExtraRequestData struct {
  XMLName xml.Name `xml:"extraRequestData" json:"-"`
  ExtensionDefinition
}

type ExtraRequestParameter struct {
  XMLName xml.Name `xml:"extraRequestParameter" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type ExtraResponseData struct {
  XMLName xml.Name `xml:"extraResponseData" json:"-"`
  ExtensionDefinition
}

type FacetedResults struct {
  XMLName xml.Name `xml:"facetedResults" json:"-"`
  facet.FacetedResultsDefinition
}

type FacetParameters struct {
  XMLName xml.Name `xml:"facetParameters" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type HttpAccept struct {
  XMLName xml.Name `xml:"httpAccept" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type MaximumRecords struct {
  XMLName xml.Name `xml:"maximumRecords" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type MissingValue struct {
  XMLName xml.Name `xml:"missingValue" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type NextRecordPosition struct {
  XMLName xml.Name `xml:"nextRecordPosition" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type NumberOfRecords struct {
  XMLName xml.Name `xml:"numberOfRecords" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type Path struct {
  XMLName xml.Name `xml:"path" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type QueryType struct {
  XMLName xml.Name `xml:"queryType" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Query struct {
  XMLName xml.Name `xml:"query" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Record struct {
  XMLName xml.Name `xml:"record" json:"-"`
  RecordDefinition
}

type RecordData struct {
  XMLName xml.Name `xml:"recordData" json:"-"`
  StringOrXmlFragmentDefinition
}

type RecordXMLEscaping struct {
  XMLName xml.Name `xml:"recordXMLEscaping" json:"-"`
  RecordXMLEscapingDefinition
}

type RecordPacking struct {
  XMLName xml.Name `xml:"recordPacking" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type RecordPosition struct {
  XMLName xml.Name `xml:"recordPosition" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type Records struct {
  XMLName xml.Name `xml:"records" json:"-"`
  RecordsDefinition
}

type RecordSchema struct {
  XMLName xml.Name `xml:"recordSchema" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type RenderedBy struct {
  XMLName xml.Name `xml:"renderedBy" json:"-"`
  RenderedByDefinition
}

type ResponsePosition struct {
  XMLName xml.Name `xml:"responsePosition" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type ResponseType struct {
  XMLName xml.Name `xml:"responseType" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type ResultCountPrecision struct {
  XMLName xml.Name `xml:"resultCountPrecision" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type ResultSetId struct {
  XMLName xml.Name `xml:"resultSetId" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type ResultSetIdleTime struct {
  XMLName xml.Name `xml:"resultSetIdleTime" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type ResultSetTTL struct {
  XMLName xml.Name `xml:"resultSetTTL" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type Schema struct {
  XMLName xml.Name `xml:"schema" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type SearchResultAnalysis struct {
  XMLName xml.Name `xml:"searchResultAnalysis" json:"-"`
  sra.SearchResultAnalysisDefinition
}

type SortKey struct {
  XMLName xml.Name `xml:"sortKey" json:"-"`
  SortKeyDefinition
}

type SortKeys struct {
  XMLName xml.Name `xml:"sortKeys" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type StartRecord struct {
  XMLName xml.Name `xml:"startRecord" json:"-"`
  Text uint64 `xml:",chardata" json:"#text,omitempty"`
}

type Stylesheet struct {
  XMLName xml.Name `xml:"stylesheet" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Value struct {
  XMLName xml.Name `xml:"value" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Version struct {
  XMLName xml.Name `xml:"version" json:"-"`
  VersionDefinition
}

type XQuery struct {
  XMLName xml.Name `xml:"xQuery" json:"-"`
  xcql.XcqlDefinition
}

type XSortKeys struct {
  XMLName xml.Name `xml:"xSortKeys" json:"-"`
  XSortKeysDefinition
}

