// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package sruResponse

import (
  "encoding/xml"
  diag "github.com/indexdata/xsd2goxsl/xsd/diagnostic.xsd_test"
  facet "github.com/indexdata/xsd2goxsl/xsd/facetedResults.xsd_test"
  sra "github.com/indexdata/xsd2goxsl/xsd/searchResultAnalysis.xsd_test"
  xcql "github.com/indexdata/xsd2goxsl/xsd/xcql.xsd_test"
  scan "github.com/indexdata/xsd2goxsl/xsd/scan.xsd_test"
)

type SearchRetrieveResponse struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse searchRetrieveResponse"`
  SearchRetrieveResponseDefinition
}

type ExplainResponse struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse explainResponse"`
  ExplainResponseDefinition
}

type ScanResponse struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse scanResponse"`
  scan.ScanResponseDefinition
}

type SearchRetrieveResponseDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty"`
  //  ******
  //                       version is for use in version 1.2 or earlier. It is removed in version 2.0.
  //                   ******
  NumberOfRecords uint64 `xml:"numberOfRecords,omitempty"`
  ResultSetId string `xml:"resultSetId,omitempty"`
  ResultSetIdleTime uint64 `xml:"resultSetIdleTime,omitempty"`
  //                       resultSetIdleTime is for use in version 1.2 or earlier. It is removed in version 2.0.
  Records *RecordsDefinition `xml:"records,omitempty"`
  NextRecordPosition uint64 `xml:"nextRecordPosition,omitempty"`
  EchoedSearchRetrieveRequest *EchoedSearchRetrieveRequestDefinition `xml:"echoedSearchRetrieveRequest,omitempty"`
  Diagnostics *DiagnosticsDefinition `xml:"diagnostics,omitempty"`
  ExtraResponseData []ExtensionDefinition `xml:"extraResponseData,omitempty"`
  //  ****
  // the following are new in version 2. They may not be used in version 1.2 or earlier.
  //                  
  XMLContent []byte   `xml:",innerxml,omitempty"`
  ResultSetTTL uint64 `xml:"resultSetTTL,omitempty"`
  //                       resultSetTTL replaces resultSetIdleTime in version 2.0.
  ResultCountPrecision []string `xml:"resultCountPrecision,omitempty"`
  FacetedResults []facet.FacetedResultsDefinition `xml:"facetedResults,omitempty"`
  SearchResultAnalysis []sra.SearchResultAnalysisDefinition `xml:"searchResultAnalysis,omitempty"`
}

type ExplainResponseDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty"`
  Record RecordDefinition `xml:"record"`
  EchoedExplainRequest *EchoedExplainRequestDefinition `xml:"echoedExplainRequest,omitempty"`
  Diagnostics *DiagnosticsDefinition `xml:"diagnostics,omitempty"`
  ExtraResponseData *ExtensionDefinition `xml:"extraResponseData,omitempty"`
}

type DiagnosticsDefinition struct {
  Diagnostic []diag.Diagnostic `xml:"diagnostic,omitempty"`
}

type EchoedExplainRequestDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty"`
  RecordXMLEscaping *RecordXMLEscapingDefinition `xml:"recordXMLEscaping,omitempty"`
  RecordPacking string `xml:"recordPacking,omitempty"`
  Stylesheet string `xml:"stylesheet,omitempty"`
  ExtraRequestData *ExtensionDefinition `xml:"extraRequestData,omitempty"`
}

type EchoedSearchRetrieveRequestDefinition struct {
  Version *VersionDefinition `xml:"version,omitempty"`
  QueryType string `xml:"queryType,omitempty"`
  Query string `xml:"query,omitempty"`
  XQuery []xcql.XcqlDefinition `xml:"xQuery,omitempty"`
  //  "query" is a string representation, and xQuery is a structured (e.g. XML) representation, of the query 
  StartRecord uint64 `xml:"startRecord,omitempty"`
  MaximumRecords uint64 `xml:"maximumRecords,omitempty"`
  RecordXMLEscaping *RecordXMLEscapingDefinition `xml:"recordXMLEscaping,omitempty"`
  RecordPacking string `xml:"recordPacking,omitempty"`
  RecordSchema string `xml:"recordSchema,omitempty"`
  FacetParameters string `xml:"facetParameters,omitempty"`
  //  one or more strings of form "[facetParameter]=value"  where [facetParameter] is one of the facet parameters
  ResultSetTTL uint64 `xml:"resultSetTTL,omitempty"`
  SortKeys string `xml:"sortKeys,omitempty"`
  XSortKeys []XSortKeysDefinition `xml:"xSortKeys,omitempty"`
  // "sortKeys" is a string representation, and xsortKeys is a structured (e.g. XML) representation, of the sort keys
  Stylesheet string `xml:"stylesheet,omitempty"`
  RenderedBy *RenderedByDefinition `xml:"renderedBy,omitempty"`
  ExtraRequestParameter []string `xml:"extraRequestParameter,omitempty"`
  HttpAccept []string `xml:"httpAccept,omitempty"`
  ResponseType string `xml:"responseType,omitempty"`
}

type ExtensionDefinition struct {
  XMLContent []byte   `xml:",innerxml,omitempty"`
}

type RecordDefinition struct {
  RecordSchema string `xml:"recordSchema"`
  RecordPacking string `xml:"recordPacking,omitempty"`
  //         recordPacking has different meaning when used for versions 1.2 or earlier than for 2.0 or later.
  //              
  RecordXMLEscaping *RecordXMLEscapingDefinition `xml:"recordXMLEscaping,omitempty"`
  // 				recordXMLEscaping  valid only for 2.0 or later.
  //   
  RecordData StringOrXmlFragmentDefinition `xml:"recordData"`
  RecordPosition uint64 `xml:"recordPosition,omitempty"`
  ExtraRecordData *ExtensionDefinition `xml:"extraRecordData,omitempty"`
  XMLContent []byte   `xml:",innerxml,omitempty"`
}

type RecordXMLEscapingDefinition string

const RecordXMLEscapingDefinitionString RecordXMLEscapingDefinition = "string"
const RecordXMLEscapingDefinitionXml RecordXMLEscapingDefinition = "xml"

type RecordsDefinition struct {
  Record []RecordDefinition `xml:"record,omitempty"`
}

type RenderedByDefinition string

const RenderedByDefinitionClient RenderedByDefinition = "client"
const RenderedByDefinitionServer RenderedByDefinition = "server"

type SortKeyDefinition struct {
  Path string `xml:"path"`
  Schema string `xml:"schema,omitempty"`
  Ascending bool `xml:"ascending,omitempty"`
  CaseSensitive bool `xml:"caseSensitive,omitempty"`
  MissingValue string `xml:"missingValue,omitempty"`
}

type StringOrXmlFragmentDefinition struct {
  XMLContent []byte   `xml:",innerxml,omitempty"`
}

type XSortKeysDefinition struct {
  SortKey []SortKeyDefinition `xml:"sortKey,omitempty"`
}

type VersionDefinition string

const VersionDefinition1_0 VersionDefinition = "1.0"
const VersionDefinition1_1 VersionDefinition = "1.1"
const VersionDefinition1_2 VersionDefinition = "1.2"
const VersionDefinition2_0 VersionDefinition = "2.0"

type Ascending struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse ascending"`
  Text bool `xml:",chardata"`
}

type CaseSensitive struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse caseSensitive"`
  Text bool `xml:",chardata"`
}

type Diagnostics struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse diagnostics"`
  DiagnosticsDefinition
}

type DisplayTerm struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse displayTerm"`
  Text string `xml:",chardata"`
}

type EchoedExplainRequest struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse echoedExplainRequest"`
  EchoedExplainRequestDefinition
}

type EchoedSearchRetrieveRequest struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse echoedSearchRetrieveRequest"`
  EchoedSearchRetrieveRequestDefinition
}

type ExtraRecordData struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse extraRecordData"`
  ExtensionDefinition
}

type ExtraRequestData struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse extraRequestData"`
  ExtensionDefinition
}

type ExtraRequestParameter struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse extraRequestParameter"`
  Text string `xml:",chardata"`
}

type ExtraResponseData struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse extraResponseData"`
  ExtensionDefinition
}

type FacetedResults struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse facetedResults"`
  facet.FacetedResultsDefinition
}

type FacetParameters struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse facetParameters"`
  Text string `xml:",chardata"`
}

type HttpAccept struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse httpAccept"`
  Text string `xml:",chardata"`
}

type MaximumRecords struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse maximumRecords"`
  Text uint64 `xml:",chardata"`
}

type MissingValue struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse missingValue"`
  Text string `xml:",chardata"`
}

type NextRecordPosition struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse nextRecordPosition"`
  Text uint64 `xml:",chardata"`
}

type NumberOfRecords struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse numberOfRecords"`
  Text uint64 `xml:",chardata"`
}

type Path struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse path"`
  Text string `xml:",chardata"`
}

type QueryType struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse queryType"`
  Text string `xml:",chardata"`
}

type Query struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse query"`
  Text string `xml:",chardata"`
}

type Record struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse record"`
  RecordDefinition
}

type RecordData struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse recordData"`
  StringOrXmlFragmentDefinition
}

type RecordXMLEscaping struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse recordXMLEscaping"`
  RecordXMLEscapingDefinition
}

type RecordPacking struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse recordPacking"`
  Text string `xml:",chardata"`
}

type RecordPosition struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse recordPosition"`
  Text uint64 `xml:",chardata"`
}

type Records struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse records"`
  RecordsDefinition
}

type RecordSchema struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse recordSchema"`
  Text string `xml:",chardata"`
}

type RenderedBy struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse renderedBy"`
  RenderedByDefinition
}

type ResponsePosition struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse responsePosition"`
  Text uint64 `xml:",chardata"`
}

type ResponseType struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse responseType"`
  Text string `xml:",chardata"`
}

type ResultCountPrecision struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse resultCountPrecision"`
  Text string `xml:",chardata"`
}

type ResultSetId struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse resultSetId"`
  Text string `xml:",chardata"`
}

type ResultSetIdleTime struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse resultSetIdleTime"`
  Text uint64 `xml:",chardata"`
}

type ResultSetTTL struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse resultSetTTL"`
  Text uint64 `xml:",chardata"`
}

type Schema struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse schema"`
  Text string `xml:",chardata"`
}

type SearchResultAnalysis struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse searchResultAnalysis"`
  sra.SearchResultAnalysisDefinition
}

type SortKey struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse sortKey"`
  SortKeyDefinition
}

type SortKeys struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse sortKeys"`
  Text string `xml:",chardata"`
}

type StartRecord struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse startRecord"`
  Text uint64 `xml:",chardata"`
}

type Stylesheet struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse stylesheet"`
  Text string `xml:",chardata"`
}

type Value struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse value"`
  Text string `xml:",chardata"`
}

type Version struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse version"`
  VersionDefinition
}

type XQuery struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse xQuery"`
  xcql.XcqlDefinition
}

type XSortKeys struct {
  XMLName xml.Name `xml:"http://docs.oasis-open.org/ns/search-ws/sruResponse xSortKeys"`
  XSortKeysDefinition
}

