// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//  Test schema for testing xsd2go.xsl
package family

import (
  "encoding/xml"
  utils "github.com/indexdata/go-utils/utils"
)


type Family struct {
  XMLName xml.Name `xml:"family" json:"-"`
  Father *Adult `xml:"father,omitempty" json:"father,omitempty"`
  Mother *Adult `xml:"mother,omitempty" json:"mother,omitempty"`
  Children []Children `xml:"children,omitempty" json:"children,omitempty"`
  FavChild struct {
    XMLName xml.Name `xml:"favChild" json:"-"`
    FavChild Person `xml:"favChild" json:"favChild"`
  }
  GrandmaMom *Adult `xml:"grandma_mom,omitempty" json:"grandma_mom,omitempty"`
  GrandpaMom *Adult `xml:"grandpa_mom,omitempty" json:"grandpa_mom,omitempty"`
  GrandmaDad *Adult `xml:"grandma_dad,omitempty" json:"grandma_dad,omitempty"`
  GrandpaDad *Adult `xml:"grandpa_dad,omitempty" json:"grandpa_dad,omitempty"`
  IncomeLevel IncomeLevel `xml:"incomeLevel" json:"incomeLevel"`
  Name utils.PrefixAttr `xml:"name,attr" json:"@name"`
}

type Father struct {
  XMLName xml.Name `xml:"father" json:"-"`
  Adult
}

type Mother struct {
  XMLName xml.Name `xml:"mother" json:"-"`
  Adult
}

type Adult struct {
  Person
  DrivingLicence bool `xml:"drivingLicence" json:"drivingLicence"`
}

type Person struct {
  Name string `xml:"name" json:"name"`
  Surname string `xml:"surname" json:"surname"`
  Age int `xml:"age" json:"age"`
  Height int `xml:"height" json:"height"`
  Gender Gender `xml:"gender" json:"gender"`
  Interests []string `xml:"interests,omitempty" json:"interests,omitempty"`
  FavColor string `xml:"favColor,omitempty" json:"favColor,omitempty"`
}

type Gender string

const GenderMALE Gender = "MALE"
const GenderFEMALE Gender = "FEMALE"

type ElemWithAttr struct {
  Text string `xml:",chardata" json:"#text,omitempty"`
  Attr *utils.PrefixAttr `xml:"attr,attr,omitempty" json:"@attr,omitempty"`
}


type Children struct {
  XMLName xml.Name `xml:"children" json:"-"`
  Child []Person `xml:"child,omitempty" json:"child,omitempty"`
}


type IncomeLevel string

const IncomeLevelHIGH IncomeLevel = "HIGH"
const IncomeLevelMEDIUM IncomeLevel = "MEDIUM"
const IncomeLevelLOW IncomeLevel = "LOW"

