// Code generated by xsd2go.xsl; DO NOT EDIT.
//go:build checkxsd

//     Search Web Services searchRetrieve Version 1.0
//     OASIS Standard
//     30 January 2013
//     Source: http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/schemas/
//     Copyright (c) OASIS Open 2013.  All Rights Reserved.
// Editor: Ray Denenberg, Library of Congress.  rden@loc.gov
// *****
package xcql

import (
  "encoding/xml"
)

type Xcql struct {
  XMLName xml.Name `xml:"xcql" json:"-"`
  XcqlDefinition
}

type XcqlDefinition struct {
  Prefixes *PrefixesDefinition `xml:"prefixes,omitempty" json:"prefixes,omitempty"`
  Triple TripleDefinition `xml:"triple" json:"triple"`
  SortKeys *SortKeysDefinition `xml:"sortKeys,omitempty" json:"sortKeys,omitempty"`
}

type PrefixesDefinition struct {
  Prefix []PrefixDefinition `xml:"prefix,omitempty" json:"prefix,omitempty"`
}

type PrefixDefinition struct {
  Name string `xml:"name" json:"name"`
  Identifier string `xml:"identifier" json:"identifier"`
}

type TripleDefinition struct {
  SearchClause *SearchClauseDefinition `xml:"searchClause,omitempty" json:"searchClause,omitempty"`
  Boolean *BooleanPlusModifier `xml:"Boolean,omitempty" json:"Boolean,omitempty"`
  LeftOperand *OperandDefinition `xml:"leftOperand,omitempty" json:"leftOperand,omitempty"`
  RightOperand *OperandDefinition `xml:"rightOperand,omitempty" json:"rightOperand,omitempty"`
}

type SortKeysDefinition struct {
  Key []KeyDefinition `xml:"key,omitempty" json:"key,omitempty"`
}

type BooleanPlusModifier struct {
  Value BooleanValue `xml:"value" json:"value"`
  Modifiers *ModifiersDefinition `xml:"modifiers,omitempty" json:"modifiers,omitempty"`
}

type BooleanValue string

const BooleanValueAnd BooleanValue = "and"
const BooleanValueOr BooleanValue = "or"
const BooleanValueNot BooleanValue = "not"
const BooleanValueProx BooleanValue = "prox"

type KeyDefinition struct {
  Index string `xml:"index" json:"index"`
  Modifiers ModifiersDefinition `xml:"modifiers" json:"modifiers"`
}

type ModifierDefinition struct {
  Type string `xml:"type" json:"type"`
  Comparison string `xml:"comparison,omitempty" json:"comparison,omitempty"`
  Value string `xml:"value,omitempty" json:"value,omitempty"`
}

type ModifiersDefinition struct {
  Modifier []ModifierDefinition `xml:"modifier,omitempty" json:"modifier,omitempty"`
}

type OperandDefinition struct {
  SearchClause *SearchClauseDefinition `xml:"searchClause,omitempty" json:"searchClause,omitempty"`
  Triple *TripleDefinition `xml:"triple,omitempty" json:"triple,omitempty"`
}

type SearchClauseDefinition struct {
  Term string `xml:"term,omitempty" json:"term,omitempty"`
  Index string `xml:"index,omitempty" json:"index,omitempty"`
  Relation *ValuePlusModifier `xml:"relation,omitempty" json:"relation,omitempty"`
}

type ValuePlusModifier struct {
  Value string `xml:"value" json:"value"`
  Modifiers *ModifiersDefinition `xml:"modifiers,omitempty" json:"modifiers,omitempty"`
}

type Boolean struct {
  XMLName xml.Name `xml:"Boolean" json:"-"`
  BooleanPlusModifier
}

type Comparison struct {
  XMLName xml.Name `xml:"comparison" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Identifier struct {
  XMLName xml.Name `xml:"identifier" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Index struct {
  XMLName xml.Name `xml:"index" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Key struct {
  XMLName xml.Name `xml:"key" json:"-"`
  KeyDefinition
}

type LeftOperand struct {
  XMLName xml.Name `xml:"leftOperand" json:"-"`
  OperandDefinition
}

type Modifier struct {
  XMLName xml.Name `xml:"modifier" json:"-"`
  ModifierDefinition
}

type Modifiers struct {
  XMLName xml.Name `xml:"modifiers" json:"-"`
  ModifiersDefinition
}

type Name struct {
  XMLName xml.Name `xml:"name" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Prefix struct {
  XMLName xml.Name `xml:"prefix" json:"-"`
  PrefixDefinition
}

type Prefixes struct {
  XMLName xml.Name `xml:"prefixes" json:"-"`
  PrefixesDefinition
}

type Relation struct {
  XMLName xml.Name `xml:"relation" json:"-"`
  ValuePlusModifier
}

type RightOperand struct {
  XMLName xml.Name `xml:"rightOperand" json:"-"`
  OperandDefinition
}

type SearchClause struct {
  XMLName xml.Name `xml:"searchClause" json:"-"`
  SearchClauseDefinition
}

type SortKeys struct {
  XMLName xml.Name `xml:"sortKeys" json:"-"`
  SortKeysDefinition
}

type Term struct {
  XMLName xml.Name `xml:"term" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Type struct {
  XMLName xml.Name `xml:"type" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

type Triple struct {
  XMLName xml.Name `xml:"triple" json:"-"`
  TripleDefinition
}

type Value struct {
  XMLName xml.Name `xml:"value" json:"-"`
  Text string `xml:",chardata" json:"#text,omitempty"`
}

